Update compile

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -11,18 +11,18 @@ ENV_DIR=$3
 PROCFILE=$(cat "${ENV_DIR}/PROCFILE")
 
 if [[ -z "${PROCFILE}" ]]; then
-    echo "PROCFILE was not set. Aborting" | indent
+    echo "Heroku.yaml was not set. Aborting" | indent
     exit 1
 fi
 
-cp "${BUILD_DIR}/${PROCFILE}" "${BUILD_DIR}/Procfile"
+cp "${BUILD_DIR}/${PROCFILE}" "${BUILD_DIR}/heroku.yml"
 
 if ! [ $? ]; then
-    echo "FAILED to copy a Procfile" | indent
+    echo "FAILED to copy a Heroku.yaml" | indent
     exit 1
 fi
 
-echo "Copied ${PROCFILE} as Procfile successfully" | indent
+echo "Copied ${PROCFILE} as Heroku.yaml successfully" | indent
 
 APP_DIR=$(dirname "${BUILD_DIR}/${PROCFILE}")
 
@@ -30,3 +30,30 @@ if [[ -f "${APP_DIR}/app.json" ]]; then
     cp "${APP_DIR}/app.json" "${BUILD_DIR}/app.json"
     echo "Copied ${APP_DIR}/app.json as app.json successfully" | indent
 fi
+
+usage() {
+  echo "OVERVIEW: Build apps according to BUILD_ENV value. Meant to be used for Heroku deployment"
+  exit
+}
+
+if [ "$1" = '-h' ] || [ "$1" = '--help' ]; then
+  usage
+fi
+
+(
+  PROJECT_ROOT="$(cd $(dirname $0)/..; pwd)"
+
+  cd $PROJECT_ROOT
+
+  if [ "$BUILD_ENV" = "web-portal" ]; then
+    yarn workspaces focus @modmd/frontends
+    yarn workspace @modmd/frontends build:internal-portal
+    
+  elif [ "$BUILD_ENV" = "api" ]; then
+    yarn workspaces focus @modmd/api
+    yarn workspace @modmd/api build:internal-portal
+  else
+    echo "Error: no build config for INATO_BUILD_ENV value '$INATO_BUILD_ENV'"
+    exit 1
+  fi
+)
